version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    labels:
      - "vue"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      vue:
        patterns:
          - "@vue*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    labels:
      - "node"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
